### ISSUE TITLE
store.on is not a function

### ISSUE THREAD

**Issue by redgang** [crossjs/plato#13]
升级到vuex(^1.0.0-rc)报错
![image](https://cloud.githubusercontent.com/assets/15260914/16646237/a354d0be-445b-11e6-946d-cde884e7157f.png)
官方给出的是store. subscribe？是否有问题？

**Comment by crossjs** [comment]
应该是 1.0.0-rc.2 把 on 废弃了。1.0.0-rc 是没有问题的。稍后修复
