### ISSUE TITLE
Rewrite UI Components

### ISSUE THREAD

**Issue by crossjs** [crossjs/plato#18]
WIP: branch faq

**Comment by crossjs** [comment]
now in branch next

**Comment by crossjs** [comment]
目标：方便拼装，应对多变的需求。
方案：尽量少的封装，尽量多的灵活。

**Comment by lynzz** [comment]
速度好快，已有模有样了 👍

**Comment by kagawagao** [comment]
可以直接用`class`代替`cls`

**Comment by crossjs** [comment]
done!
> 可以直接用class代替cls

特性放到 https://github.com/crossjs/plato/projects/2 中管理
