### ISSUE TITLE
import { env, auth, progress } from 'vx/getters' 获取不到env，auth, progress，都为undefined

### ISSUE THREAD

**Issue by redgang** [crossjs/plato#6]
1、修改webpack配置前，获取vx/constants的数据
![image](https://cloud.githubusercontent.com/assets/15260914/16193060/7dca9854-371f-11e6-8515-88e6ab416d34.png)

修改webpack配置后，获取vx/constants的数据
![image](https://cloud.githubusercontent.com/assets/15260914/16193040/6c157ba6-371f-11e6-9540-cbe96fa66f07.png)

package.json中绝大部分引用plato配置
![image](https://cloud.githubusercontent.com/assets/15260914/16193246/8822ee40-3720-11e6-942f-5c0607da72e1.png)

主要想引用src的目录结构及相关思想，并简化server文件夹，去掉test配置，自己做了一个类似.tools的构建环境（koa，babel，postcss），但vx中获取到constants、getters等获取数据格式不对，导致页面无法正常显示。

2、css文件不写后缀名（我的工程会报错），怎么配置不会引起报错
![image](https://cloud.githubusercontent.com/assets/15260914/16193405/9e378226-3721-11e6-88ac-37cdf21cef4c.png)

请帮忙看看，谢谢！

**Comment by crossjs** [comment]
@redgang 最好能提供代码。
1、第一个问题，可以检查下 .babelrc 是否有配置 `add-module-exports`，如果有，是不是你引用的方式不对，比如使用了 `import * as constants from '...'`
2、第二个问题，`webpack/index.js` 是否配置了 `resolve.extensions`

**Comment by redgang** [comment]
@crossjs 
第二个问题是resolve.extensions中缺少.css配置，加上已经解决，tks！

第一个问题，将.babelrc文件引用你的文件，安装相关依赖后，问题依然还是存在，似乎add-module-exports这个插件没起作用，export default回来的值都含有default对象，webpack是否需要做相关配置？

注：src里面都是引用plato里面的文件（除了ajax的插件改用vue-resource）及结构。

**Comment by crossjs** [comment]
没代码不好确定。

**Comment by redgang** [comment]
原因找到了，在webpack loader js配置中，重复添加了babel配置，导致add-module-exports没生效，现在已可以正常运行。

tks，too！

再请教个问题，ajax是否可用官方提供的vue-resource，此plugins与官方提供的功能差异大吗？

**Comment by crossjs** [comment]
ajax 插件是针对我现在的一些业务情况做的封装，还在继续完善。
建议你根据自己的喜好，选用合适的插件。
